//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxDb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxDb.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [Test001](
        ///    [Id] INTEGER CONSTRAINT [sqlite_master_PK_Test001] PRIMARY KEY NOT NULL,
        ///    [Field1] nvarchar(50) NOT NULL,
        ///    [Field2] nvarchar(50) NOT NULL,
        ///    [Field3] nvarchar(50) NOT NULL,
        ///	[Field4] INTEGER NULL,
        ///	[Field5] numeric(53,0) NULL 
        ///);
        ///
        ///CREATE TABLE [Test002](
        ///    [Id] INTEGER CONSTRAINT [sqlite_master_PK_Test002] PRIMARY KEY NOT NULL,
        ///	[Test003_Id] INTEGER NULL,
        ///	[Test004_Id] INTEGER NULL,
        ///    [Name] nvarchar(50) NOT NULL
        ///);
        ///
        ///CREATE TABLE [Test002_Test004](
        ///    [Id] INTEGER CO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlCeSchema {
            get {
                return ResourceManager.GetString("SqlCeSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [Test001](
        ///    [Id] INTEGER CONSTRAINT [sqlite_master_PK_Test001] PRIMARY KEY NOT NULL,
        ///    [Field1] text NOT NULL,
        ///    [Field2] text NOT NULL,
        ///    [Field3] text NOT NULL,
        ///	[Field4] INTEGER NULL,
        ///	[Field5] numeric(53,0) NULL 
        ///);
        ///
        ///CREATE TABLE [Test002](
        ///    [Id] INTEGER CONSTRAINT [sqlite_master_PK_Test002] PRIMARY KEY NOT NULL,
        ///	[Test003_Id] INTEGER NULL,
        ///	[Test004_Id] INTEGER NULL,
        ///    [Name] text NOT NULL
        ///);
        ///
        ///CREATE TABLE [Test002_Test004](
        ///    [Id] INTEGER CONSTRAINT [sqlite_master_PK_Test0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLiteSchema {
            get {
                return ResourceManager.GetString("SQLiteSchema", resourceCulture);
            }
        }
    }
}
